In [2]:
# For tips on running notebooks in Google Colab, see
# https://pytorch.org/tutorials/beginner/colab
%matplotlib inline

**Learn the Basics** \|\| [Quickstart](quickstart_tutorial.html) \|\|
[Tensors](tensorqs_tutorial.html) \|\| [Datasets &
DataLoaders](data_tutorial.html) \|\|
[Transforms](transforms_tutorial.html) \|\| [Build
Model](buildmodel_tutorial.html) \|\|
[Autograd](autogradqs_tutorial.html) \|\|
[Optimization](optimization_tutorial.html) \|\| [Save & Load
Model](saveloadrun_tutorial.html)

Learn the Basics
================

Authors: [Suraj Subramanian](https://github.com/subramen), [Seth
Juarez](https://github.com/sethjuarez/), [Cassie
Breviu](https://github.com/cassiebreviu/), [Dmitry
Soshnikov](https://soshnikov.com/), [Ari
Bornstein](https://github.com/aribornstein/)

Most machine learning workflows involve working with data, creating
models, optimizing model parameters, and saving the trained models. This
tutorial introduces you to a complete ML workflow implemented in
PyTorch, with links to learn more about each of these concepts.

We\'ll use the FashionMNIST dataset to train a neural network that
predicts if an input image belongs to one of the following classes:
T-shirt/top, Trouser, Pullover, Dress, Coat, Sandal, Shirt, Sneaker,
Bag, or Ankle boot.

[This tutorial assumes a basic familiarity with Python and Deep Learning
concepts.]{.title-ref}

Running the Tutorial Code
-------------------------

You can run this tutorial in a couple of ways:

-   **In the cloud**: This is the easiest way to get started! Each
    section has a \"Run in Microsoft Learn\" and \"Run in Google Colab\"
    link at the top, which opens an integrated notebook in Microsoft
    Learn or Google Colab, respectively, with the code in a fully-hosted
    environment.
-   **Locally**: This option requires you to setup PyTorch and
    TorchVision first on your local machine ([installation
    instructions](https://pytorch.org/get-started/locally/)). Download
    the notebook or copy the code into your favorite IDE.

How to Use this Guide
---------------------

If you\'re familiar with other deep learning frameworks, check out the
[0. Quickstart](quickstart_tutorial.html) first to quickly familiarize
yourself with PyTorch\'s API.

If you\'re new to deep learning frameworks, head right into the first
section of our step-by-step guide: [1. Tensors](tensor_tutorial.html).

::: {.toctree maxdepth="2" hidden=""}
quickstart\_tutorial tensorqs\_tutorial data\_tutorial
transforms\_tutorial buildmodel\_tutorial autogradqs\_tutorial
optimization\_tutorial saveloadrun\_tutorial
:::


In [3]:
import torch
import numpy as np

## **Tensor**


In [4]:
# create tensor from list
data = [
    [1,2],
    [3,4]
]

# tensor type
x_data=torch.tensor(data)

print(x_data)

tensor([[1, 2],
        [3, 4]])


In [5]:
# create tensor from numpy
np_data = np.array(data)
x_np = torch.from_numpy(np_data)

print(x_np)


tensor([[1, 2],
        [3, 4]])


In [6]:
# from another tensor
x_one = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_one} \n")

x_zero = torch.zeros_like(x_data)
print(f"Zeros Tensor: \n {x_zero} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Zeros Tensor: 
 tensor([[0, 0],
        [0, 0]]) 



In [7]:
print(x_data.shape)
print(x_data.dtype)
print(x_data.device)

torch.Size([2, 2])
torch.int64
cpu


In [8]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
print(rand_tensor)

tensor([[0.1017, 0.5073, 0.8541],
        [0.0128, 0.4360, 0.5574]])


In [15]:
new_data = [
    [1,2,5],
    [3,4,6]
]

tensor = torch.tensor(new_data, dtype=torch.float)

result = torch.mul(tensor, tensor)
print(result)


tensor([[ 1.,  4., 25.],
        [ 9., 16., 36.]])


In [17]:
# Bridge with numpy

shape = (3,3)
t = torch.rand(shape)
print(F"tensor: {t}")

n = t.numpy()
print(f"numpy: {n}")

tensor: tensor([[0.0167, 0.9885, 0.0708],
        [0.8326, 0.5416, 0.6637],
        [0.4582, 0.0379, 0.5636]])
numpy: [[0.01672566 0.9884505  0.07080257]
 [0.8326454  0.5416452  0.6637008 ]
 [0.4581958  0.03785634 0.5635762 ]]


In [18]:
n[0, 0] = 10

print(F"tensor: {t}")
print(f"numpy: {n}")

tensor: tensor([[10.0000,  0.9885,  0.0708],
        [ 0.8326,  0.5416,  0.6637],
        [ 0.4582,  0.0379,  0.5636]])
numpy: [[10.          0.9884505   0.07080257]
 [ 0.8326454   0.5416452   0.6637008 ]
 [ 0.4581958   0.03785634  0.5635762 ]]
